---
abstract: 'Alien package for the libmagic library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  Module::Load: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-LibMagic
recommends:
  Inline: '0.67'
  Inline::C: '0.62'
requires:
  Alien::Base: '0.038'
  Path::Tiny: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/zmughal-p5CPAN/p5-Alien-LibMagic
  repository: https://github.com/zmughal-p5CPAN/p5-Alien-LibMagic.git
version: 0.002_01
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.29'
  requires:
    share:
      Archive::Tar: '0'
      Config: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mojo::DOM: '0'
      Mojolicious: '7.00'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
